default_stages: [commit]
repos:
  - repo: https://github.com/yyang-even/yyLinuxScripts
    rev: 4492250e7b5ae5dd153a0aa2ff4eaf8da64e0525
    hooks:
      - id: shfmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
        stages: [commit]
